name: inject variables
on:
  push:
    branches:
      - master
      - release/** # 项目暂时使用 release 分支作为发布分支
    tags:
      - v* # 所有以 v 开头的 tag
jobs:
  inject-variables-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: exec inject env script
        env:
          FUNDEBUG_SHOP_APIKEY: ${{ secrets.FUNDEBUG_SHOP_APIKEY }}
        run: sh ./scripts/inject-env.sh